title: Tia Vafeas
email: shvafeas@gmail.com
description: >-
  Biostatistician passionate about real-world data and healthcare analytics.

url: "https://shvaf.github.io" # your domain
baseurl: "" # keep this empty

theme: null
remote_theme: alshedivat/al-folio

# Navigation
navbar-links:
  About Me: "about"
  Projects: "projects"
  CV: "cv"
